<?php
	define('1', 'Eureka');
	define('2', 'Alkhwarism');
	define('3', 'Codeshow');
	define('4', 'Infinitum');
	define('5', 'CFresh');
	define('6', 'Confondere');
	define('7', 'QwertyWars');
	define('8', 'Perplexuz');
	define('9', 'biomeda');
	define('10', 'ITQuiz');
	define('11', 'technobooz');
	define('12', 'NuVision');
	define('13', 'VFlare');
	define('14', 'Platzen');
	define('15', 'Coldfire');
	define('16', 'PenaltyShootout');
	define('17', 'AIPod');
	define('18', 'Xplorer');
	define('19', 'Bolt');
	define('20', 'BlackBox');
	define('21', 'ElectronicTreasureHunt');
	define('22', 'Technofault');
	define('23', 'Webkriti');
	define('24', 'Backbone');
	define('25', 'CounterStrike');
	define('26', 'Dota2');
	define('27', 'Fifa15');
	define('28', 'SplitSecond');
	define('29', 'riddlonics');
	define('30', 'Wolf of 2311');
	define('31', 'PS I Love Electronics');
	define('32', 'Thought Bazaar');
	define('33', 'Hackathon');
	define('34', 'exhibition');
?>